apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  labels:
    app: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: {{ .Values.movieService.image }}:{{ .Values.movieService.tag }}
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for DB..." &&
              sleep 30 &&  # Attendre 30 secondes avant de commencer
              uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: {{ .Values.movieService.databaseUri }}
          volumeMounts:
            - name: movie-service-volume
              mountPath: /app
      volumes:
        - name: movie-service-volume
          hostPath:
            path: /home/ubuntu/exam_devops_jenkins/movie-service
            type: Directory
