apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
        - name: movie-db
          image: {{ .Values.postgresMovie.image }}
          ports:
            - containerPort: 5432
              name: movie-db
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresMovie.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresMovie.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresMovie.db }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: movie-db-data
      volumes:
        - name: movie-db-data
          emptyDir: {}