apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 8060;

      location /api/v1/movies/ {
        proxy_pass http://movie-service;
      }

      location /api/v1/cast/ {
        proxy_pass http://cast-service;
      }
    }