apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 8060
      targetPort: 8060
      nodePort: 30080  # Port accessible depuis l'extérieur